# Generated by Django 4.2.4 on 2023-09-27 23:19

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto de la pregunta')),
            ],
        ),
            migrations.CreateModel(
            name='ElegirRespuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(verbose_name='correcta?', default=False, null = False)),
                ('texto', models.TextField(verbose_name='texto respuesta')),
                (('Pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Pregunta'))),
            ],
        ),]
